### ISSUE TITLE
support for bootstrap 4

### ISSUE THREAD

**Issue by thekalinga** [wcwhitehead/bootstrap-3-snippets#16]
This is a request more than an issue.

Is it possible to add bootstrap4 snippets aswell along with bootstrap 3 in a separate repo?

**Comment by Learn-Digital-Audio** [comment]
That would be very cool :)

**Comment by thekalinga** [comment]
I have created the plugin myself & is published to vscode extensions repo [here](https://marketplace.visualstudio.com/items?itemName=thekalinga.bootstrap4-vscode)
