### ISSUE TITLE
Question: Converting Sublime snippets to VS Code

### ISSUE THREAD

**Issue by mikewheaton** [wcwhitehead/bootstrap-3-snippets#2]
I'm working on a similar project to this one, where I'd like to produce a large number of snippets for Visual Studio Code. You mentioned that the [Twitter Bootstrap 3 Snippets](https://github.com/JasonMortonNZ/bs3-sublime-plugin) plugin is the source of these snippets, and I'm wondering how you converted from Sublime format to Visual Studio Code.

For example, the Sublime snippet is:
```
<snippet>
	<content><![CDATA[
<ol class="breadcrumb">
	<li>
		<a href="${1:#}">${2:Home}</a>
	</li>
	${3:<li>
		<a href="#">Link</a>
	</li>}
	<li class="active">${4:Current}</li>
</ol>
]]></content>
	<tabTrigger>bs3-breadcrumbs</tabTrigger>
</snippet>
```

While in Visual Studio Code, everything inside `CDATA` has been collapsed into a single string with tab and line return characters.
```
\n<ol class=\"breadcrumb\">\n\t<li>\n\t\t<a href=\"${1:#}\">${2:Home}</a>\n\t</li>\n\t${3:<li>\n\t\t<a href=\"#\">Link</a>\n\t</li>}\n\t<li class=\"active\">${4:Current}</li>\n</ol>\n
```

Could you share how you went about doing this?

**Comment by wcwhitehead** [comment]
Hi Mike,

I looked at my code and I noticed that unlike your example, I do not have any CDATA sections. However, the Yeoman generator did convert all of the Sublime snippets into single line strings, which I left mostly untouched.

Have you tried debugging your snippet set and inserted one into a document? Do the new line, tab, etc. characters format appropriately?

**Comment by mikewheaton** [comment]
What Yeoman generator did you use? I've been looking for something like that. I'd love to just throw a collection of HTML snippets at it and get the nicely formatted strings with tab and new line characters.

_____________________________

**Comment by wcwhitehead** [comment]
The one mentioned here: https://code.visualstudio.com/docs/tools/yocode

**Comment by mikewheaton** [comment]
Not sure how I missed the snippets option, thanks! I'll play around with this.





On Sun, Feb 14, 2016 at 2:39 PM -0800, "William Whitehead" <notifications@github.com<mailto:notifications@github.com>> wrote:


The one mentioned here: https://code.visualstudio.com/docs/tools/yocode<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcode.visualstudio.com%2fdocs%2ftools%2fyocode&data=01%7c01%7cmiwhea%40microsoft.com%7cbc6831b6527b4aaad0c508d3358fa2b7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=eUi5%2bbY1IZDvP1Tk0F8P7lkQYOzBAAeOfQbJab0zCYA%3d>

-
